#!/usr/bin/env python3
"""
Interactive Docker setup assistant for OilRisk_Alert.

This script writes a root .env file for docker compose and can optionally
start the full stack after configuration is complete.
"""

import secrets
import shutil
import string
import subprocess
import sys
from datetime import datetime
from getpass import getpass
from pathlib import Path
from typing import Dict, Optional


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
ENV_EXAMPLE_PATH = ROOT / ".env.example"


def print_header(title: str) -> None:
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


def ask_text(prompt: str, default: str = "", allow_empty: bool = False) -> str:
    while True:
        suffix = f" [{default}]" if default else ""
        value = input(f"{prompt}{suffix}: ").strip()
        if not value:
            value = default
        if value or allow_empty:
            return value
        print("该项不能为空，请重新输入。")


def ask_secret(prompt: str, default: str = "", allow_empty: bool = False) -> str:
    while True:
        suffix = " [留空则自动生成]" if not default and not allow_empty else ""
        value = getpass(f"{prompt}{suffix}: ").strip()
        if not value:
            value = default
        if value or allow_empty:
            return value
        print("该项不能为空，请重新输入。")


def ask_yes_no(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{prompt} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False
        print("请输入 y 或 n。")


def generate_password(length: int = 20) -> str:
    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def backup_existing_env() -> Optional[Path]:
    if not ENV_PATH.exists():
        return None
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = ROOT / f".env.backup.{timestamp}"
    shutil.copy2(ENV_PATH, backup)
    return backup


def write_env_file(values: Dict[str, str]) -> None:
    lines = [
        "# Auto-generated by scripts/setup_docker.py",
        "# This file is consumed by docker compose.",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    lines.append("")
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


def docker_available() -> bool:
    try:
        subprocess.run(
            ["docker", "compose", "version"],
            cwd=ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return True
    except Exception:
        return False


def start_stack() -> int:
    print("\n开始执行 docker compose up --build -d ...\n")
    completed = subprocess.run(
        ["docker", "compose", "up", "--build", "-d"],
        cwd=ROOT,
    )
    return completed.returncode


def main() -> int:
    print_header("OilRisk Docker 一键配置向导")
    print("这个脚本会为当前项目生成根目录 .env 文件，并可选地直接启动 Docker 栈。")
    print("如果根目录已存在 .env，脚本会先自动备份。")
    print(f"项目根目录: {ROOT}")

    if not ENV_EXAMPLE_PATH.exists():
        print("❌ 缺少 .env.example，仓库状态不完整。")
        return 1

    print_header("基础端口配置")
    frontend_port = ask_text("前端对外端口", "5173")
    backend_port = ask_text("后端对外端口", "8080")
    python_port = ask_text("Python 推理服务对外端口", "5000")
    mysql_port = ask_text("MySQL 对外端口", "3306")

    print_header("数据库配置")
    mysql_database = ask_text("数据库名", "oilrisk")
    mysql_user = ask_text("应用数据库用户名", "oilrisk")
    mysql_password = ask_secret("应用数据库密码", allow_empty=True) or generate_password()
    mysql_root_password = ask_secret("MySQL root 密码", allow_empty=True) or generate_password()

    print_header("实时数据源配置")
    full_mode = ask_yes_no("是否配置实时金融数据源和自动采集", True)
    if full_mode:
        fred_api_key = ask_text("FRED API Key", allow_empty=False)
        eia_api_key = ask_text("EIA API Key", allow_empty=False)
        use_proxy = ask_yes_no("是否为外部数据源配置 HTTP/HTTPS 代理", False)
        if use_proxy:
            http_proxy = ask_text("HTTP_PROXY，例如 http://127.0.0.1:7890")
            https_proxy = ask_text("HTTPS_PROXY，回车则沿用 HTTP_PROXY", http_proxy)
        else:
            http_proxy = ""
            https_proxy = ""
    else:
        fred_api_key = ""
        eia_api_key = ""
        http_proxy = ""
        https_proxy = ""

    backfill_on_startup = "true" if ask_yes_no("容器启动时自动检测并回填历史缺口", False) else "false"
    collect_on_startup = "true" if ask_yes_no("容器启动时立即执行一次全量采集", False) else "false"

    print_header("大模型配置")
    enable_llm = ask_yes_no("是否配置大模型 API（不配置则使用 Mock 文本）", False)
    if enable_llm:
        llm_api_key = ask_text("LLM API Key", allow_empty=False)
        llm_api_url = ask_text("LLM API URL", "https://apis.iflow.cn/v1/chat/completions")
        llm_api_model = ask_text("LLM 模型名", "qwen3-max")
    else:
        llm_api_key = ""
        llm_api_url = "https://apis.iflow.cn/v1/chat/completions"
        llm_api_model = "qwen3-max"

    cors_origins = ",".join(
        [
            f"http://localhost:{frontend_port}",
            f"http://127.0.0.1:{frontend_port}",
        ]
    )

    values = {
        "COMPOSE_PROJECT_NAME": "oilrisk-alert",
        "MYSQL_PORT": mysql_port,
        "MYSQL_DATABASE": mysql_database,
        "MYSQL_USER": mysql_user,
        "MYSQL_PASSWORD": mysql_password,
        "MYSQL_ROOT_PASSWORD": mysql_root_password,
        "FRONTEND_PORT": frontend_port,
        "BACKEND_PORT": backend_port,
        "PYTHON_ENGINE_PORT": python_port,
        "APP_CORS_ALLOWED_ORIGINS": cors_origins,
        "FRED_API_KEY": fred_api_key,
        "EIA_API_KEY": eia_api_key,
        "HTTP_PROXY": http_proxy,
        "HTTPS_PROXY": https_proxy,
        "YF_BATCH_SIZE": "5",
        "YF_BATCH_DELAY": "2.0",
        "YF_SINGLE_DELAY": "1.5",
        "BACKFILL_ON_STARTUP": backfill_on_startup,
        "COLLECT_ON_STARTUP": collect_on_startup,
        "LLM_API_KEY": llm_api_key,
        "LLM_API_URL": llm_api_url,
        "LLM_API_MODEL": llm_api_model,
    }

    backup = backup_existing_env()
    write_env_file(values)

    print_header("配置完成")
    if backup is not None:
        print(f"已备份旧配置: {backup}")
    print(f"已生成配置文件: {ENV_PATH}")
    print(f"前端访问地址: http://localhost:{frontend_port}")
    print("MySQL 初始化表结构会在首次启动容器时自动执行。")

    if not docker_available():
        print("\n❌ 未检测到可用的 docker compose。")
        print("请先安装 Docker Desktop，然后手动执行:")
        print("  docker compose up --build -d")
        return 0

    if ask_yes_no("是否现在直接启动 Docker 容器", True):
        code = start_stack()
        if code == 0:
            print("\n✅ Docker 容器已启动。")
            print(f"打开 http://localhost:{frontend_port} 即可访问前端。")
        else:
            print("\n❌ docker compose 启动失败，请检查终端输出。")
        return code

    print("\n你可以稍后手动执行:")
    print("  docker compose up --build -d")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\n已取消。")
        sys.exit(130)
